### ISSUE TITLE
No module "KasaSmartPowerStrip"

### ISSUE THREAD

**Issue by Phangzs** [p-doyle/Python-KasaSmartPowerStrip#1]
I was trying to run the code, but it gave a me an error, saying "No module 'KasaSmartPowerStrip'". I tried using pip install KasaSmartPowerStrip but it couldn't find the library apparently.

**Comment by p-doyle** [comment]
You have to have KasaSmartPowerStrip.py in the same folder as where you are running the example code from.  This library is not available from pip.

**Comment by Phangzs** [comment]
Now that they're in the same folder, and I've run the KasaSmartPowerStrip.py before the setup, and I get: 

Traceback (most recent call last):
  File "example code.py", line 6, in <module>
    power_strip = SmartPowerStrip('192.168.0.1')
  File "C:\Users\chess\OneDrive\Desktop\Voice Thing\KasaSmartPowerStrip.py", line 19, in __init__
    sys_info = self.get_system_info()
  File "C:\Users\chess\OneDrive\Desktop\Voice Thing\KasaSmartPowerStrip.py", line 44, in get_system_info
    return self._udp_send_command('{"system":{"get_sysinfo":{}}}')
  File "C:\Users\chess\OneDrive\Desktop\Voice Thing\KasaSmartPowerStrip.py", line 209, in _udp_send_command
    client_socket.sendto(self._encrypt_command(command, prepend_length=False), addr)
TypeError: a bytes-like object is required, not 'str'

The example code I ran is:


from KasaSmartPowerStrip import SmartPowerStrip


power_strip = SmartPowerStrip('192.168.0.1')


(using python 2.7)

**Comment by p-doyle** [comment]
Are you sure you're using python 2.7?  That is the same error I get when trying to run it with python3.

**Comment by p-doyle** [comment]
I updated the code to work with both Python3 and Python2.7.  Can you re-download and try again?

**Comment by Phangzs** [comment]
Hi, the code now works, only one problem left. After disconnecting and reconnecting, I can no longer control the power strip. I'm not sure how to fix this, but I'm guessing it's to use a dynamic DNS, but if you could give me more information, that would be so helpful. 
Again, thanks so much now that it works!

**Comment by p-doyle** [comment]
After disconnecting and reconnecting to what?  Are you able to ping the strip?

**Comment by Phangzs** [comment]
Sorry for the delayed response.
I am now able to connect to the power strip anytime I am on my wifi. My question was if there was any way to be able to connect to the strip while on a different network. Is it possible to be able to access the power strip even while I am away? 
Thanks in advance!

**Comment by p-doyle** [comment]
The simplest way would be to just use the Kasa app as that provides access from anywhere.  You should be able to use the python script and the Kasa app simultaneously, though I haven't tested that.  Other more complicated methods include setting up a VPN on your router so that you can connect to your home network from anywhere or setting up port forwarding on your router but that would be dangerous as the power strip doesn't do any kind of authentication.  Either method is way beyond the scope of this issue though and there are plenty of resources available online.

**Comment by Phangzs** [comment]
Thank you for helping me set up the power strip!
