### ISSUE TITLE
toggle_plugs doesn't seem to work

### ISSUE THREAD

**Issue by sdb9696** [p-doyle/Python-KasaSmartPowerStrip#11]
Were you ever able to get this work to toggle multiple plugs at once? It only seems to only toggle the first device in the `child_ids` list.  I've been testing on a hs300 btw.

**Comment by keepalivedev** [comment]
I've never had any issue toggling multiple plugs at once.  My HS300 is several years old at this point though so it is possible the software has changed.  Mine is version 1.0.6 Build 180627 Rel.081000.

**Comment by p-doyle** [comment]
I have never had any issue toggling multiple plugs at once, though my HS300 is several years old at this point.  It is possible the software has been updated, I am still on version 1.0.6 Build 180627 Rel.081000.

**Comment by sdb9696** [comment]
Many thanks
