### ISSUE TITLE
How do you find the IP of the powerstrip after you set wifi credentials?

### ISSUE THREAD

**Issue by JustinMBrown** [p-doyle/Python-KasaSmartPowerStrip#2]
>After setting the WiFi info it should restart and then connect to your network at which point
you should be able to begin using it.

This worked, but now I can't use 192.168.0.1 to connect to the device. I'm sure my router gave it some random dynamic IP, so is there anyway I can search for that IP using its mac address or something? Is there a script to discover all TP-link devices on the network? Any help is appreciated.

**Comment by p-doyle** [comment]
The easiest way would be to check the DHCP leases on your router.

**Comment by JustinMBrown** [comment]
I agree, but it's a corporate network and I don't have access to the router unfortunately. [This repo](https://github.com/GadgetReactor/pyHS100) seems to have a discover feature which I'm gonna try out if I can't find the IP via the mac address.

**Comment by JustinMBrown** [comment]
I ended up using the mac address to find the IP. On initial setup I save the mac to a config file, and then on the next run, I call nmap from inside python to get the IP using that mac address.
