### ISSUE TITLE
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 1021 (char 1020)

### ISSUE THREAD

**Issue by rjsears** [p-doyle/Python-KasaSmartPowerStrip#3]
Hello - 

Just wanted to let you know that I was receiving this error while talking to a TP-Link HS300:

`json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 1021 (char 1020)`

I was able to correct the issue by changing line 211 from this:

`data, server = client_socket.recvfrom(1024)`

to this:

`data, server = client_socket.recvfrom(2048)`

**Comment by p-doyle** [comment]
Can you send an example of what the raw message was?  Its an easy update, just not something I encountered during my testing so I'm curious.

**Comment by rjsears** [comment]
You bet -

here it is:

Traceback (most recent call last):
  File "/var/www/fish_tank_control/tank_control/tank_control_master.py",
line 25, in <module>
    import power_strip
  File "/var/www/fish_tank_control/tank_control/utilities/power_strip.py",
line 13, in <module>
    power_strip = SmartPowerStrip(system_info.tank_name)
  File
"/var/www/fish_tank_control/tank_control/utilities/KasaSmartPowerStrip.py",
line 19, in __init__
    sys_info = self.get_system_info()
  File
"/var/www/fish_tank_control/tank_control/utilities/KasaSmartPowerStrip.py",
line 44, in get_system_info
    return self._udp_send_command('{"system":{"get_sysinfo":{}}}')
  File
"/var/www/fish_tank_control/tank_control/utilities/KasaSmartPowerStrip.py",
line 213, in _udp_send_command
    return json.loads(self._decrypt_command(data))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1
column 1021 (char 1020)

Process finished with exit code 1




                      Richard J. Sears
                      ATP ASMEL/Rotor, CFI, CFII, MEI
                      G-V / CE-525S / CE-500 / S-70

**Comment by p-doyle** [comment]
Oh sorry I mean the message that came in from the HS300.  Wondering what caused the increased length from what I've seen in the past.

**Comment by rjsears** [comment]
Absolutely, but not really sure what you are looking for - I am not getting
anything back at all from the power strip on the console. How can I grab
that info for you?


root@scripts:~/kasa_power_strip# python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from KasaSmartPowerStrip import SmartPowerStrip
>>> power_strip = SmartPowerStrip('75planted')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/kasa_power_strip/KasaSmartPowerStrip.py", line 19, in __init__
    sys_info = self.get_system_info()
  File "/root/kasa_power_strip/KasaSmartPowerStrip.py", line 44, in
get_system_info
    return self._udp_send_command('{"system":{"get_sysinfo":{}}}')
  File "/root/kasa_power_strip/KasaSmartPowerStrip.py", line 213, in
_udp_send_command
    return json.loads(self._decrypt_command(data))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1
column 1021 (char 1020)
>>>






                      Richard J. Sears
                      ATP ASMEL/Rotor, CFI, CFII, MEI
                      G-V / CE-525S / CE-500 / S-70

**Comment by p-doyle** [comment]
Ah nevermind, don't worry about it.  I've updated the code.

Thanks for reporting!

**Comment by rjsears** [comment]
No problem at all, thanks for your great code :-)


                      Richard J. Sears
                      ATP ASMEL/Rotor, CFI, CFII, MEI
                      G-V / CE-525S / CE-500 / S-70
