### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by brianx87** [p-doyle/Python-KasaSmartPowerStrip#4]
Having trouble connecting, new to python so I'm uncertain of how to amend the issue. I've ran `KasaSmartPowerStrip.py` from the commandline with the KP303 connected to my Windows Desktop at 192.168.0.100, when I run `power_strip = SmartPowerStrip('192.168.1.1'`) from the Python shell I get the following errors.

```
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    power_strip = SmartPowerStrip('192.168.1.1')
  File "C:\Python\Python38\Lib\KasaSmartPowerStrip.py", line 19, in __init__
    sys_info = self.get_system_info()
  File "C:\Python\Python38\Lib\KasaSmartPowerStrip.py", line 44, in get_system_info
    return self._udp_send_command('{"system":{"get_sysinfo":{}}}')
  File "C:\Python\Python38\Lib\KasaSmartPowerStrip.py", line 211, in _udp_send_command
    data, server = client_socket.recvfrom(2048)
socket.timeout: timed out``
```

The IP I need to add to `power_strip = SmartPowerStrip('X.X.X.X'`)` should be the IP for the gateway router?

**Comment by p-doyle** [comment]
The default IP for the strip when connected to its WiFi is 192.168.0.1.

**Comment by brianx87** [comment]
> The default IP for the strip when connected to its WiFi is 192.168.0.1.

Yes I know, I have already ran the` power_strip = SmartPowerStrip('X.X.X.X')` command using 192.168.0.1 with the same result. I've run commands as follows `from KasaSmartPowerStrip import SmartPowerStrip` then `power_strip = SmartPowerStrip('X.X.X.X')` where I've tested the default IP, gateway router IP and the static IP I had assigned by my DHCP server all ending in the same result as above.

**Comment by p-doyle** [comment]
Okay... the exception you linked shows 192.168.1.1 so I wasn't sure.  If you are on windows I would try opening a command windows and running `ipconfig` to check your network config and verify that you are still connected to the strip's WiFi.

**Comment by brianx87** [comment]
> IPv4 Address. . . . . . . . . . . : 192.168.0.100
> Subnet Mask . . . . . . . . . . . : 255.255.255.0
> Default Gateway . . . . . . . . . : 192.168.0.1

That's the connection there, I keep getting the same errors returned concerning lines 19, 44 and 211. I haven't modified `KasaSmartPowerStrip.py ` in any way just ran it though commandline then with python ran `from KasaSmartPowerStrip import SmartPowerStrip` followed by `power_strip = SmartPowerStrip('X.X.X.X')`

**Comment by p-doyle** [comment]
While connected to the wifi I would try to do `ping 192.168.0.1` from a command window to make sure the strip is even reachable.
