### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by amccombsahce** [p-doyle/Python-KasaSmartPowerStrip#5]
I am running on raspberry pi 3+. It's been working fine for over a year. I got a second HS300,  I also did an 'apt update' and everything fell apart, I fixed all but now I get this error. This error is from the new HS300. Both power strips show Hardware verion 1.0, and Firmware version 1.0.19. Both also have the same name on the network "HS300" because I can't find directions to change it.
This seems to only occur with get_sysinfo with the second one as I can toggle to switches without errors.

HS300 two
Traceback (most recent call last):
  File "a.py", line 12, in <module>
    power_strip2 = SmartPowerStrip('192.168.1.201')
  File "/home/amccombs/KasaSmartPowerStrip.py", line 21, in __init__
    sys_info = self.get_system_info()
  File "/home/amccombs/KasaSmartPowerStrip.py", line 46, in get_system_info
    return self._udp_send_command('{"system":{"get_sysinfo":{}}}')
  File "/home/amccombs/KasaSmartPowerStrip.py", line 213, in _udp_send_command
    data, server = client_socket.recvfrom((2048))
socket.timeout: timed out

here is a.py:
#!/usr/bin/python3

import json

from KasaSmartPowerStrip import SmartPowerStrip

#print("HS300 one\n")
#power_strip1 = SmartPowerStrip('192.168.1.181')
#print(power_strip1.get_system_info())

print("HS300 two\n")
power_strip2 = SmartPowerStrip('192.168.1.201')
print(power_strip2.get_system_info())

**Comment by p-doyle** [comment]
Hmm.. can you ping 192.168.1.201?

**Comment by amccombsahce** [comment]
yes, it's ping'able.

I worked with it some more; get_system_info works more reliable when using Windows 10 than linux (both Ubuntu 20.04 LTS and Raspbian GNU/Linux 9 (stretch)) and now the code is modified by adding the device_id and now it works more reliably and get fewer timeouts. 

power_strip2 = SmartPowerStrip('192.168.1.201')
power_strip2. device_id = "[device id]"
print(power_strip2.get_system_info())

This does not make sense to me because I needed to do get_system_info to get the id, then feed it back into get_system_info for it to work, and udp is just broadcasting to a specific ip.

**Comment by amccombsahce** [comment]
I added a print statement, 

def _udp_send_command(self, command):
 print("\nKasaSmartPowerStrip._udp_send_command self.device_id[{0}]".format(self.device_id))

the output is:
KasaSmartPowerStrip._udp_send_command self.device_id[None]

why is it  'None' when I entered it in the power_strip2.device_id = "[device id]" line?

**Comment by p-doyle** [comment]
I'm not sure exactly, but if you know the device id you can supply it when initializing the SmartPowerStrip class like:
`power_strip = SmartPowerStrip('192.168.1.201', device_id=<your device id>)`

If a device_id isn't supplied then it will do a get_system_info() when doing `power_strip = SmartPowerStrip('192.168.1.201')` so there is no need to do it yourself.  If it crashes there then it likely wasn't able to connect to the power strip and nothing after that is going to work anyway.

**Comment by amccombsahce** [comment]
when you init the SmartPowerStrip with the device_id then the get_plug_info shows:
`TypeError: 'NoneType' object is not subscriptable`

All I want to do is to see if the plug_num is on or off, and this is the mess that I have:

#!/usr/bin/python3
import sys
from builtins import bytes

from KasaSmartPowerStrip import SmartPowerStrip

power_strip_1 = SmartPowerStrip('192.168.1.210')
power_strip_2 = SmartPowerStrip('192.168.1.210', device_id = <enter your device id>)



outlet_number = 2

print(power_strip_1.get_realtime_energy_info(plug_num=int(outlet_number)))
print(power_strip_2.get_realtime_energy_info(plug_num=int(outlet_number)))

abc20201019102230 = power_strip_1.get_plug_info(plug_num=int(outlet_number))
print(abc20201019102230)

for abc20201019102231 in abc20201019102230:
    abc20201019102232 = abc20201019102231['state']
    print(abc20201019102232)
    if abc20201019102232 == '0':
        print("off")
    if abc20201019102232 == '1':
        print("on")
    if abc20201019102232 == 0:
        print("Off")
    if abc20201019102232 == 1:
        print("On")


abc20201019102240 = power_strip_2.get_plug_info(plug_num=int(outlet_number))
print(abc20201019102240)

for abc20201019102241 in abc20201019102240:
    abc20201019102242 = abc20201019102241['state']
    print(abc20201019102242)
    if abc20201019102242 == '0':
        print("off")
    if abc20201019102242 == '1':
        print("on")
    if abc20201019102242 == 0:
        print("Off")
    if abc20201019102242 == 1:
        print("On")

**Comment by amccombsahce** [comment]
works better with device_id but still get some errors.
