### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lriesebos** [p-doyle/Python-KasaSmartPowerStrip#6]
Hi @p-doyle ,

I am a grad student and we would like to use your code to control a power strip in our lab. We use a bunch of build-infrastructure to guarantee our code is reproducible and tested, but currently we can not include your software due to the lack of a license.

Would you be willing to attach a license to your software? For us, a more permissive license would make it easier (e.g. Apache 2.0), but obviously the choice is completely up to you.

Regards,
Leon

**Comment by p-doyle** [comment]
Sure!  Added Apache 2.0
