### ISSUE TITLE
get_plug_info is 'TypeError: 'NoneType' object is not subscriptable' when SmartPowerStrip(ip,device_id) is used

### ISSUE THREAD

**Issue by amccombsahce** [p-doyle/Python-KasaSmartPowerStrip#7]
When init the SmartPowerStrip with the device_id then the get_plug_info shows:
`TypeError: 'NoneType' object is not subscriptable`

All I want to do is to see if the plug_num is on or off, and this is the mess that I have:

#!/usr/bin/python3
import sys
from builtins import bytes

from KasaSmartPowerStrip import SmartPowerStrip

power_strip_1 = SmartPowerStrip('192.168.1.210')
power_strip_2 = SmartPowerStrip('192.168.1.210', device_id = 'enter your device id')

outlet_number = 2

print(power_strip_1.get_realtime_energy_info(plug_num=int(outlet_number)))
print(power_strip_2.get_realtime_energy_info(plug_num=int(outlet_number)))

abc20201019102230 = power_strip_1.get_plug_info(plug_num=int(outlet_number))
print(abc20201019102230)

for abc20201019102231 in abc20201019102230:
abc20201019102232 = abc20201019102231['state']
print(abc20201019102232)
if abc20201019102232 == '0':
print("off")
if abc20201019102232 == '1':
print("on")
if abc20201019102232 == 0:
print("Off")
if abc20201019102232 == 1:
print("On")

abc20201019102240 = power_strip_2.get_plug_info(plug_num=int(outlet_number))
print(abc20201019102240)

for abc20201019102241 in abc20201019102240:
abc20201019102242 = abc20201019102241['state']
print(abc20201019102242)
if abc20201019102242 == '0':
print("off")
if abc20201019102242 == '1':
print("on")
if abc20201019102242 == 0:
print("Off")
if abc20201019102242 == 1:
print("On")

**Comment by p-doyle** [comment]
So it looks like there was a bug in the code if you provided the device_id.  Can you get the latest version and see if you still have an issue?

**Comment by amccombsahce** [comment]
Fixed, thank you.
