### ISSUE TITLE
toggle_plugs crashes when number of plugs in the array goes above 4

### ISSUE THREAD

**Issue by kfechter** [p-doyle/Python-KasaSmartPowerStrip#8]
When running this script, I get the below error whenever the number of plugs in the array goes above 4.

`Traceback (most recent call last):
  File ".\kasa_control.py", line 14, in <module>
    power_strip.toggle_plugs(args.state, plug_num_list=args.plugs)
  File "KasaSmartPowerStrip.py", line 102, in toggle_plugs
    return self.send_command(all_relay_command, self.protocol)
  File "KasaSmartPowerStrip.py", line 124, in send_command
    return self._tcp_send_command(command)
  File "KasaSmartPowerStrip.py", line 192, in _tcp_send_command
    sock_tcp.send(self._encrypt_command(command))
  File "KasaSmartPowerStrip.py", line 222, in _encrypt_command
    result = b'\0\0\0' + bytes([len(string)])
ValueError: bytes must be in range(0, 256)`

if I call my script with args.plugs = [1, 2, 3, 5], it works. if I call it with [1, 2, 3, 4, 5] or any combination of 5 or 6 plugs, it crashes.

**Comment by p-doyle** [comment]
It looks like I was using a hack-y way to get the length of the command that only works when the command is 256 bytes or less.  I just made a new commit, can you see if the current version works?

**Comment by kfechter** [comment]
bam, script works with arrays greater than size 4 now. 

awesome, thanks! i'll mark this closed.
